# unit 23. 2차원 리스트 사용하기

In [1]:
# 리스트[행][열]
# 리스트[row][column]
# 리스트[세로][가로]

In [2]:
a = [[10, 20], [30, 40], [50, 60]]
a

[[10, 20], [30, 40], [50, 60]]

In [3]:
a[1][1]  #파이썬은 이것만 지원하는데

40

In [4]:
# Numpy array 빅데이터 인공지능하려면 넘파이필요
import numpy as np
arr = np.array(a)
arr                     #위에것보다 보기가 좀 편함 ^^

array([[10, 20],
       [30, 40],
       [50, 60]])

In [5]:
arr[1,1]      #넘파이_행렬을 컴마로 분류

40

In [7]:
arr[1:, 1:]      #넘파이_2차원 슬라이싱 우어어어어어어1!!!!!1부터 끝까지

array([[40],
       [60]])

In [8]:
arr[0:, 1:]  

array([[20],
       [40],
       [60]])

In [9]:
# 톱니형 리스트  이런것도 가능합니다~ 들쑥날쑥 행열 값이 안같아도 되요. 리스트에서는 자유로와~~
a = [[1],
     [2, 3],
     [4, 5, 6],
     [7, 8],
     [9]]

In [10]:
len(a)

5

In [11]:
for row in a:       #사람이 보기쉽게한건가..?for문써서
    for element in row:
        print(element, end=' ')
    print()

1 
2 3 
4 5 6 
7 8 
9 


In [12]:
for i in range(len(a)):     #인덱스로 뽑아보자
    for k in range(len(a[i])):
        print(a[i][k], end=' ')
    print()

1 
2 3 
4 5 6 
7 8 
9 


# for 반복문으로 2차원 리스트 만들기

In [13]:
a = []    # 겉에 빈 리스트 생성
 
for i in range(3):
    line = []              # 안쪽 리스트로 사용할 빈 리스트 생성
    for j in range(2):
        line.append(0)     # 안쪽 리스트에 0 추가
    a.append(line)         # 전체 리스트에 안쪽 리스트를 추가append
 
print(a)

[[0, 0], [0, 0], [0, 0]]


In [14]:
# (u22에 있던 예제활용) 3 x 6 list에 1~6 랜덤값 채우기
import random as rd
mat = []
for i in range(3):        # 행의 갯수
    row = []              #들어가기전 빈 리스트 만들기
    for k in range(6):    #열의 갯수_ 표현식의 안쪽루프로 넣음
        row.append(rd.randint(1,6))
    mat.append(row)

In [17]:
# 표현식으로 만들기 위에것과 같음
#리스트안에 리스트가 들어와야해.6개씩 3번을만들라
mc= [[rd.randint(1,6) for k in range(6)] for i in range(3)] 
mc

[[1, 2, 1, 1, 6, 4], [4, 1, 3, 4, 3, 6], [2, 3, 4, 3, 3, 2]]

### 2차원 리스트의 복사

In [20]:
a = [[10, 20], [30, 40]]
b = a.copy()
b

[[10, 20], [30, 40]]

In [21]:
b[1][1] = 100          #40을 100으로 변경. a도 바뀌었다!
a

[[10, 20], [30, 100]]

In [22]:
import copy               #deepcopy하면  (잘안쓰이긴하는데)
a = [[10, 20], [30, 40]]
b = copy.deepcopy(a)

In [23]:
b[1][1] = 100          #40을 100으로 변경. a는 바뀌지않는다.
a

[[10, 20], [30, 40]]

# 코딩도장 퀴즈

### 1. 다음 중 가로 2, 세로 2 크기의 2차원 리스트를 만드는 방법
##### a = [[10, 20], [30, 40]]

#### 가로 2, 세로 2 크기의 2차원 리스트는 리스트 = [[값, 값], [값, 값]] 형식으로 만듭니다.

### 2. 다음 중 리스트 a = [[10, 20], [30, 40, 50], [60]]에서 
### 60을 출력하는 방법
#### print(a[2][0])
#### 리스트 [[10, 20], [30, 40, 50], [60]]에서 
#### 60은 세로 인덱스 2, 가로 인덱스 0에 있으므로 
#### print(a[2][0])으로 출력하면 됩니다.

### 3. 다음 중 for 반복문을 사용하여 2차원 리스트 a의 모든 요소를 출력하는 방법
#### for i in a:
####    for j in i:
####        print(j)
#### for로 2차원 리스트 a의 모든 요소를 출력할 때는 for i in a:와 같이 전체 리스트에서 가로 한 줄씩 꺼내 옵니다. 다시 for j in i:와 같이 가로 한 줄 i에서 요소를 하나씩 꺼내면 됩니다.

### 4. while 반복문을 사용하여 2차원 리스트의 모든 요소를 출력할 때
.......쩝 ㅋ
#### while i < len(a):와 같이 세로 크기만큼 반복했을 때는 while j < len(a[i]):와 같이 가로 크기만큼 반복하면 됩니다. 가로 크기는 len(a[i])와 같이 리스트에 세로 인덱스를 지정하여 len으로 구합니다.


### 5. 다음 중 리스트 [[0, 0, 0], [0, 0, 0], [0, 0, 0]]를 만드는 방법으로 올바른 것을 모두
#### 방법1) [[0 for j in range(3)] for i in range(3)]
#### 방법2) [[0, 0, 0] for i in range(3)]

#### 리스트 표현식으로 2차원 리스트를 만들 때는 먼저 [0 for j in range(3)]와 같이 0을 3번 반복하여 [0, 0, 0]으로 만들고 다시 for i in range(3)로 [0, 0, 0]을 3번 반복하여 [[0, 0, 0], [0, 0, 0], [0, 0, 0]]으로 만듭니다. 또는, [0, 0, 0] for i in range(3)와 같이 리스트 자체를 3번 반복해도 됩니다.